### ISSUE TITLE
Watcom makefiles: DOS4GW vs X32VM

### ISSUE THREAD

**Issue by Lethja** [gvanem/Watt-32#117]
In the process of working on #114 I noticed when running `configur.bat watcom` the script prints the following message
```
Generating Watcom makefiles, directories, errnos and dependencies
Run wmake to make target(s):
E.g. "wmake -h -f watcom_s.mak" for small model (16-bit)
     "wmake -h -f watcom_l.mak" for large model (16-bit)
     "wmake -h -f watcom_3.mak" for small model (32-bit DOS4GW)
     "wmake -h -f watcom_f.mak" for flat model  (DOS4GW)
     "wmake -h -f watcom_x.mak" for flat model  (X32VM)
     "wmake -h -f watcom_w.mak" for Win32
```
and both `watcom_f.mak` and `watcom_x.mak` are generated however, the files are 100% identical
```
$ md5sum WATCOM_F.MAK WATCOM_X.MAK
0470eaefb49401a55bac1684235e2001  WATCOM_F.MAK
0470eaefb49401a55bac1684235e2001  WATCOM_X.MAK
```
Is this a redundant file?

**Comment by gvanem** [comment]
> Is this a redundant file?

Possibly. I don't remember now why there are 2 of these.

**Comment by Lethja** [comment]
> Possibly. I don't remember now why there are 2 of these.

I'll implement code to generate `watcom_f.mak` for now. `watcom_x.mak` can always be added later if a historic difference between the two is uncovered
