### ISSUE TITLE
Multiple issues related to building Watt-32 with Open Watcom in DOS  

### ISSUE THREAD

**Issue by mateuszviste** [gvanem/Watt-32#3]
This is a list of little things I reported through the Watt-32 mailing list in February 2019. I fetched now the latest Watt-32 master version from the github repo and I can confirm that all these issues are still present.

It is about building Watt-32 using the watcom compiler under real mode DOS.

------------------------------
1. "cannot redirect"
The configur.bat script complains...
![watt32-cannotredirect](https://user-images.githubusercontent.com/9503501/72937245-0b612e00-3d69-11ea-9621-f557da3167e6.png)

The reason is that directory "build/watcom" does not exist. The solution is simple: mkdir build/watcom

2. "too many arguments" when makefile calls "echo"
![watt32-wmake-fail](https://user-images.githubusercontent.com/9503501/72937404-5b3ff500-3d69-11ea-90eb-e6cb6487ae65.png)

As a quick hack I simply removed the cflags.h target from the makefile and created it by hand... That's not a solution of course. Not sure what the solution could be here - the problem lies, I think, in the maximum number of arguments that the shell is able to pass to a command (echo, in this case).

3. Then this problem popped out:

"cflags_buf.h not found"

In fact, the makefile was creating the cflags_buf.h all right, but then
wmake was unable to find it. It seems to be a 8+3 problem. I renamed cflags_buf.h to cflagsbf.h (and replaced all references to it in all source files), and the problem went away. Since the rest of the Watt-32 source base is 8+3 compatible, perhaps could the cflags_buf.h thing be simplified to 8+3 as well?

4. build/watcom/syserr.c(108): Error! E1011: Symbol '__syserr00' has not
been declared

This one I am truly clueless about. I mean, I do confirm that __syserr00
was missing in the syserr.c file, but why it is missing is a mystery to
me, since this is some kind of auto-generated file. Curiously, I did not
run into this problem when compiling under the windows platform. The
hack I applied is very simple, I naively added this to syserr.c:

char __syserr00[] = "";

....and then, at last, Watt-32 compiled.

**Comment by gvanem** [comment]
> The reason is that directory "build/watcom" does not exist. 

I think there is an issue with  `make_dirs()` in `mkmake.c`
If you're able to rebuild `util\mkmake.exe` for DOS/Watcom, please do 
(I'm on Win-10 and is not able to).

For the other issues, I'll try to build for Watcom/Win32 (but I thin Watcom stinks).

**Comment by gvanem** [comment]
BTW.  For a `wmake -f watcom_l.mak`, I'm getting:
```
wcc386 ip4_in.c @build\watcom\large\wcc386.arg -fo=build\watcom\large\ip4_in.obj
ip4_in.c(235): Error! E1119: Internal compiler error 97
```
I've tried with these versions:
* Version 2.0 2.0 beta Apr 27 2014
* Version 2.0 beta Dec 25 2018

The same issue for both. Arg!

**Comment by gvanem** [comment]
> Symbol '__syserr00' has not been declared

Again this is an issue with your `util/wc_err.exe`; it needs to be rebuilt. And I'm not able to since I'm on Win-10. 

AFAICR, the reason for using 3 digits, was that some Win-SDK added more `<errno.h>` values.

**Comment by mateuszviste** [comment]
> I think there is an issue with `make_dirs()` in `mkmake.c`
> If you're able to rebuild `util\mkmake.exe` for DOS/Watcom, please do

I'm not - complains about some "slang" missing... but compiling this with openwatcom is not necessary. If I understand correctly, the exe that is present in the git repo is something that you build yourself using djgpp, right? No need to change that. But still, it fails to create the build\watcom\* paths... For a test, I compiled a test program with only the make_dirs() function, where I tried to mimic what configur.bat + mkmake do, and it works good (meaning it succeeds in creating the entire path):

````
#include <errno.h>
#include <stdio.h>
#include <dir.h>
#include <io.h>
#include <unistd.h>  /* Assumes only djgpp is used for __MSDOS__ */
#include <sys/stat.h>

#define SLASH '\\'
#define MKDIR(D) mkdir ((D), 0777)

void str_replace(char c, char c2, char *d) {
}

int make_dirs (char *dir)
{
  char *p;
  int ret;

#if (SLASH == '/')
  str_replace ('\\', SLASH, dir);
#else
  str_replace ('/', SLASH, dir);
#endif

  for (p = dir + 1; *p; ++p)
  {
    if (*p == SLASH)
    {
      *p = '\0';
      ret = MKDIR (dir);
      *p = SLASH;
      if (ret != 0 && errno != EEXIST)
         return ret;
    }
  }
  return MKDIR (dir);
}

int main(int argc, char **argv) {
  make_dirs("build\\watcom\\large");
  return(0);
}
````

Now that I think of it, perhaps the mkmake.exe tool is simply outdated, like (apparently) wc_err.exe? Would you happen to have the necessary libslang.a file around? If so, could you please add it to the git repo? Then I should (hopefully) be able to rebuild it using DJGPP.

> BTW. For a wmake -f watcom_l.mak, I'm getting:
>
> wcc386 ip4_in.c @build\watcom\large\wcc386.arg -fo=build\watcom\large\ip4_in.obj
> ip4_in.c(235): Error! E1119: Internal compiler error 97

I didn't get that far recently, but I suspect it might be related to you using a potentially not-super-stable Watcom version. Myself I'm using the last stable version, ie. 1.9. Last time I checked (February 2019), it did manage to compile Watt-32 2.2 rev 11, once I bypassed the build process glitches (it did not work very well afterwards, but that's another story, first things first).

> Again this is an issue with your util/wc_err.exe; it needs to be rebuilt. And I'm not able to since I'm
> on Win-10.

mmm, where should I look for the wc_err.exe source code? I looked around in the git tree, but cannot locate anything by the name wc_err.c. Is it somewhere else?

**Comment by gvanem** [comment]
It's built from `util/errnos.c` using `util/errno.mak`. Try this:
```
cd util
wmake -f errnos.mak wc_err.exe
```

> Myself I'm using the last stable version, ie. 1.9. 

I tried this too (dated 25 May 2010). Causes the same *: Internal compiler error 97* too :-(.

**Comment by gvanem** [comment]
> "too many arguments" when makefile calls "echo"

I've added a patch for this. Try this: https://github.com/gvanem/Watt-32/commit/d670177e313e3c60dcec78c2c8e42a195e4ed65c

**Comment by gvanem** [comment]
> Would you happen to have the necessary libslang.a file around? 

I added it here: [dj-libslang.zip](https://github.com/gvanem/Watt-32/files/4104750/dj-libslang.zip).

**Comment by mateuszviste** [comment]
> > "too many arguments" when makefile calls "echo"
> 
> I've added a patch for this. Try this: [d670177](https://github.com/gvanem/Watt-32/commit/d670177e313e3c60dcec78c2c8e42a195e4ed65c)

That's clever, and it does solve the "too many arguments" problem. Yay!

> I added it here: [dj-libslang.zip](https://github.com/gvanem/Watt-32/files/4104766/dj-libslang.zip)
> 
> _Edit_: Added `slang.h` to the .zip too (in case you don't have it). It is ver. "pre2.3.2-13".

Thanks! I compiled [MKMAKE.EXE](https://github.com/gvanem/Watt-32/files/4105606/mkmake.zip) without any troubles now, and indeed - it works as expected (ie. the build/watcom/* directories are all properly created).

Sadly, WATT-32 compilation fails on ip4_in.c with a similar message to the one you described:
![image](https://user-images.githubusercontent.com/9503501/73026578-f2707f80-3e31-11ea-93d8-067fb2474fb3.png)

I am 100% sure that the version 2.2 rel 11 was compiling fine last year, so something in the code must have changed, that makes wcc angry... Will try looking into that.

**Comment by mateuszviste** [comment]
okay, I see -you changed the compiler from "wcc" to "wcc386" in the mean time... I reverted to wcc and the "internal compiler error" problem is gone.
````
Index: src/makefile.all
===================================================================
--- src/makefile.all    (revision 207)
+++ src/makefile.all    (working copy)
@@ -468,8 +468,8 @@
 # And possibly add '-0' to 'CFLAGS'.
 #
 @ifdef SMALL
-CC      = wcc386
-CFLAGS  = -ms -os -zc -s -bt=dos
+CC      = wcc
+CFLAGS  = -ms -0 -os -zc -s -bt=dos
 AFLAGS  = -bt=dos
 TARGET  = ..\lib\wattcpws.lib
 OBJDIR  = build\watcom\small
@@ -476,8 +476,8 @@
 MAKEFIL = watcom_s.mak
 
 @elifdef LARGE
-CC      = wcc386
-CFLAGS  = -ml -os -zc -s -bt=dos
+CC      = wcc
+CFLAGS  = -ml -0 -os -zc -s -bt=dos
 AFLAGS  = -bt=dos
 TARGET  = ..\lib\wattcpwl.lib
 OBJDIR  = build\watcom\large
````

Is there a reason for using wcc386? I might be wrong, but I think that noone uses Watcom nowadays for protected mode things... gcc/clang (or DJGPP on DOS) are all better. Watcom is an outstanding tool for compiling real-mode (16 bit) things, though (ie. using wcc).

**Comment by mateuszviste** [comment]
> It's built from `util/errnos.c` using `util/errno.mak`. Try this:
> 
> ```
> cd util
> wmake -f errnos.mak wc_err.exe
> ```

It worked, thanks again! Here is the updated [WC_ERR.EXE](https://github.com/gvanem/Watt-32/files/4105750/wc_err.zip)

Now the compilation process succeeds again, that's super cool. I guess we can close this issue, since all the items are good now:

1. "cannot redirect" -> SOLVED through recompilation of MKMAKE.EXE
2. "too many arguments" -> SOLVED through d670177
3. "cflags_buf.h" -> SOLVED through 928fe02
4. "Symbol __syserr00" -> SOLVED through recompilation of WC_ERR.EXE
5. "Internal error XX" -> SOLVED through reverting to wcc (in lieu of wcc386)

**Comment by gvanem** [comment]
> Is there a reason for using wcc386? 

Then maybe I've misunderstood their differences. I thought the `-ml` should generate a *Large* program for both.

> "cannot redirect" -> SOLVED through recompilation of MKMAKE.EXE
> "Internal error XX" -> SOLVED through reverting to wcc (in lieu of wcc386)

I've committed those.

**Comment by mateuszviste** [comment]
> > Is there a reason for using wcc386?
> 
> Then maybe I've misunderstood their differences. I thought the `-ml` should generate a _Large_ program for both.

You are right about the memory model. The difference is that (as far as I understand) wcc386 assumes a 386 CPU, ie. it uses plenty of extra registers, performs specific optimizations, etc. Hence the resulting binary requires a 386+ CPU. I wonder why would one compile a "LARGE" memory model program if he has a 386 CPU? Much faster and more efficient to run protected mode in such setup - and then wcc386 is in direct competition with DJGPP. wcc, on the other hand, is able to generate 8086 code, and it's very good at it.

**Comment by sezero** [comment]
> > The reason is that directory "build/watcom" does not exist.
> 
> I think there is an issue with `make_dirs()` in `mkmake.c`

Sorry for joining in late. If it's still relevant: mkmake in 2.2.11 is broken,
I made several updates to it in my fork, along with an slang solution and
working binaries, here: https://github.com/sezero/watt32/tree/2.2.11-sezero

**Comment by gvanem** [comment]
After further trial and error, I fail to find the cause of this bug. It will have to wait.

**Comment by gvanem** [comment]
@mateuszviste If you feel these issues are solved, feel free to close this issue.

**Comment by mateuszviste** [comment]
yes they are - definitely. master Watt-32 builds perfectly now under 16-bit DOS. Thank you for your patience!
