### ISSUE TITLE
gnu tools tab character stupidity

### ISSUE THREAD

**Issue by jmalak** [gvanem/Watt-32#31]
I have a big problem with tools like MKMAKE etc, that they are GNU centric and use GNU stupidity with tab character on begining of line. 
Do you plan to use some other tools then GNU which are working without dependency on leading tab character?

**Comment by jmalak** [comment]
Next problem with MKMAKE if backslash is it is last nonblank character on line then it is used as concatenation character. Do you know how I can use baskslash character on end of line that is used as regular character, not as line continuation character.

**Comment by gvanem** [comment]
I cannot change how GNU operates; a rule needing a `<tab>`. Is that a problem in your editor?
I use Crimson Editor with visible tabs. I see no problem with that.

> Do you plan to use some other tools then GNU ...

Like what? Must be something that users of all OS'es can use. So any CMake, Python based stuff etc. is out of the question.

>  Do you know how I can use baskslash character on end of line that is used as regular character, not as line continuation character.

I don't follow (?). Is your editor leaving trailing white-space at *end-of-line*?
Maybe you can use `wmake -ms -f watcom_?.mak`.

**Comment by jmalak** [comment]
Sorry I was not exact. I didn't mean compilers but tools used for building.
If watt-32 is for DOS and Windows only you can use any make tools which are able handle appropriate compilers which you support.
Main problem is with MKMAKE that it uses @ character on text beggining for its own processing.
if there is command starting with @ then MKMAKE process it as own command.
It is not problem with GNU where it must be, but problem is with wmake make file where no such restriction and commands can have leading spaces not tab.
I must add tab character for wmake make file even if it is not required by wmake, it requires MKMAKE tool.

**Comment by jmalak** [comment]
Could be acceptable for you replace MKMAKE by other tool which do similar work?
By example Open Watcom project use for similar tasks simple tool wsplice which is used for creation various variant of text file from one source text file. It is multiplatform and works simple transparent way that copy filtered lines to output as is without any processing. It uses markers line with keywords and simple rules to process them.

**Comment by jmalak** [comment]
Below is sample source text file which is processed by wsplice and output is controled by keyword.
control lines are starting with double dots and word as symbol next cen be keyword which is used for conditional processing. Control lines are separated from output lines.
```
#ifndef ___VA_LIST_DEFINED
#define ___VA_LIST_DEFINED
:segment !INTEL_ONLY
 #ifdef __PPC__
:segment DOS
  #ifdef __NT__
   typedef char  *__va_list;
  #else
:endsegment
   typedef struct {
       char  __gpr;
       char  __fpr;
       char  __reserved[2];
       char  *__input_arg_area;
       char  *__reg_save_area;
   } __va_list;
:segment DOS
  #endif
:endsegment
 #elif defined(__AXP__)
  typedef struct {
      char  *__base;
      int   __offset;
  } __va_list;
 #elif defined(__MIPS__)
  typedef struct {
      char  *__base;
      int   __offset;
  } __va_list;
 #elif defined(_M_IX86)
:endsegment
:segment BITS16
  #if defined(__HUGE__) || defined(__SW_ZU)
:elsesegment
  #if defined(__SW_ZU)
:endsegment
   typedef char _WCFAR *__va_list[1];
  #else
   typedef char    *__va_list[1];
  #endif
:segment !INTEL_ONLY
 #endif
:endsegment
#endif
```
```
// This program reads a file and produces another according to the
// directives within the file(s) read.  The directives are:
//  (1) :include file-name
//      - includes a file
//  (2) :segment expr
//      . . .
//      {:elsesegment [expr]}
//      . . .
//      :endsegment
//      - the lines between these directives are a segment
//      - the section that is delimited by the first <expr> that is true,
//        up to the next :elsesegment or :endsegment are output.
//  (3) :keep name
//      - directs that the lines for the indicated segment are to be output,
//        when that segment is subsequently encountered
//  (4) :remove name
//      - directs that the lines for the indicated segment are to be ignored,
//        when that segment is subsequently encountered
//  (5) :: comments
//      - when the first two non-blank characters are "::" the line is treated
//        as a comment and is not written to the output file
//
```
It could simplify things, because continuation of line is not processed by this tools but by target tools etc.

**Comment by gvanem** [comment]
`mkmake` is built using S-Lang. The pre-processor character is set by:
```
SLprep_set_prefix (pt, "@");
```

So it can be something else like `!` or `%`. Try it: 
` c:\net\watt\tmp\> git clone git://git.jedsoft.org/git/slang.git`

But describe the problem you want to solve better in a PR.

*BTW:* Could be a job for [Mako](https://www.makotemplates.org/) too?

**Comment by jmalak** [comment]
first problem is pre-processor character @ which is used very frequently in wmake make files
- it is solvable by tab on begining of line
- I will try to recompile mkmake with ':' as preprocessor character which I thing is not used in makefiles

second problem is with backslash character if it is used as last non whitespace character 
- I don't know how to resolve it

**Comment by jmalak** [comment]
The problem with backslash looks like bug in MKMAKE. It translate last backslash followed by whitespaces instead of backslash imeediately before EOL.

**Comment by gvanem** [comment]
>  It translate last backslash followed by whitespaces instead of backslash imeediately before EOL.

Should be easier to fix than adding yet another tool like `wsplice`.

**Comment by jmalak** [comment]
I checked to fix mkmake utility and now it works both, backslash and ':' as pre-processor character.

Is it acceptable to change pre-processor character to ':' and do appropriate changes in all source files which are affected by this change?

**Comment by gvanem** [comment]
No, using `:` look ugly. Why not fix `mkmake.c` to suite wmake's problem. Whatever that it.

**Comment by jmalak** [comment]
It is not possible to fix it if preprocessor directives start with same character as wmake commands and leading spaces are suppress. The existing GNU tools use tab character as start of line that it is not suppressed. This is make file command otherwise it is preprocessor directive. I can stay with existing behaviour it requires put tab character on line begining if command start with @ character.

**Comment by gvanem** [comment]
Okay. It has taken ages to get those `Makefile.all` files correctly for all those targets. 
So I would be sceptic to change that.

**Comment by jmalak** [comment]
I will add note to makefile.all about it and what rules are important to wmake entries work correctly.

**Comment by jmalak** [comment]
Please, could you rewiev changes to mk* tools and if you aply it then recompile tools for Dos and Windows and update them in repository I will next add Linux version of these tools to repository.
There is important fix for continuation line, it should not affect existing configuration anyway, but it enables to modify makefiles to use cross-compilation by Watcom.

**Comment by gvanem** [comment]
Building for DOS would be hard/impossible for me. But I'll push the `util/win32/*.exe` files.
