### ISSUE TITLE
configur.sh need executable attribute

### ISSUE THREAD

**Issue by jmalak** [gvanem/Watt-32#32]
Please setup executable attribute for src/configur.sh file and submit this cange to repository.
There is missing this attribute that can not be run on Linux without local manual change.

**Comment by gvanem** [comment]
I've no idea how. I don't do Linux.

**Comment by jmalak** [comment]
it should be done by git command
git update-index --chmod=+x 'file name'
next you should submit it to repository.

Please could you correct src/makefile.all too
simply delete it localy 
next reload it from repository.
next submit it to repository

**Comment by gvanem** [comment]
Done now.

Do that crap every time? Why don't you do that locally?

**Comment by jmalak** [comment]
I do change through web interface which is simplified that can not do this low-level changes.
I will install my own copy of repository on github and then I will able to create such change request.

Anyway I checked to fix mkmake utility and now it works both, backslash and ':' as pre-processor character.

Is it acceptable to change pre-processor character to ':' and do appropriate changes in all source files which are affected by this change?
