### ISSUE TITLE
Macro 'cdecl' conflicts with gcc attribute name.

### ISSUE THREAD

**Issue by jwt27** [gvanem/Watt-32#60]
I just tried compiling my C++ code with Watt-32 in the include path, and find that it breaks due to an empty macro called `cdecl`.  This name is also used for `[[gnu::cdecl]]` (or `__attribute__((cdecl))`).  I'd like to distribute Watt-32 as part of [build-gcc](https://github.com/jwt27/build-gcc/tree/watt32), but I expect this will break a lot of code, not just my own.

I think it's very unusual to have a lowercase macro, especially for such a common keyword.  Is it possible to rename it to something uppercase, eg. `ATTR_CDECL`, or even just `CDECL`?  I see it's only used in two headers, `sys/cdefs.h` and `sys/swap.h`.

**Comment by gvanem** [comment]
Do you have a simple test-case for this? A simple C++ w/ STL or something.

**Comment by jwt27** [comment]
```c++
#include <chrono> // includes <sys/cdefs.h> via <time.h>

[[gnu::cdecl]]
void f() { }
```
will trigger the problem:
```
test.cpp:3:13: error: expected an identifier for the attribute name
    3 | [[gnu::cdecl]]
      |             ^
```

**Comment by gvanem** [comment]
How about you trying the same with clang. gcc is IMHO so bad at indication were the fault is.
But how about:
```diff
diff --git a/inc/sys/cdefs.h b/inc/sys/cdefs.h
index 6894f48..354f75d 100644
--- a/inc/sys/cdefs.h
+++ b/inc/sys/cdefs.h
@@ -161,7 +161,7 @@
   /* e.g. int NO_UNDERSCORE foo (void); */
 #endif

-#ifndef cdecl
+#if !defined(cdecl) && !defined(__cplusplus)
 #define cdecl
 #endif
```

**Comment by jwt27** [comment]
The problem isn't limited to C++.  The same issue occurs in C, and is much more insidious:
```c
#include <time.h>

__attribute__((cdecl))
void f(void) { }
```

here `__attribute__((cdecl))` turns into `__attribute__(())` after macro expansion - the whole attribute then has no effect, but it doesn't emit *any* warnings.

I think the solution is either to rename it. or to `#undef cdecl` at the end of `sys/cdefs.h`.

**Comment by gvanem** [comment]
Check your `<minwindef.h>`. Mine has a `#define cdecl` on line 81. So AFAICS, this is to blame too.
And `<minwindef.h>` gets included everywhere.

**Comment by jwt27** [comment]
I don't have this header on djgpp.  And I think "library X does it too" is not a very good argument for keeping broken behavior.
The win32 api has had more problems with leaking macros into user code, it's not exactly an example of good design.

**Comment by gvanem** [comment]
> I don't have this header on djgpp. 

I know. But does your  `[[gnu::cdecl]]` example compile on MinGW with or without Watt-32?

**Comment by jwt27** [comment]
Probably not, then.  But as I said, I don't think that's relevant.

I still don't understand why only two functions in `<sys/swap.h>` use `cdecl` whereas other functions use `W32_CDECL` or `MS_CDECL`.

**Comment by gvanem** [comment]
Now I've removed **all** `#define cdecl` (for gcc) from `sys/cdecl.h` and preprocessed this program with `gcc` and `g++`:
```c
/*
 * Preprocess this file as:
 *  $(BIN_PREFIX)gcc -dM -E -I%WATT_ROOT%/inc gcc-cdecl.c | grep " cdecl"
 *
 * or
 *   $(BIN_PREFIX)g++ -dM -E -I%WATT_ROOT%/inc gcc-cdecl.c | grep " cdecl"
 */
#include <sys/socket.h>   /* Includes <$WATT_ROOT/sys/cdecl.h> */
#include <time.h>

#ifdef __cplusplus
#include <chrono>
#endif

__attribute__((cdecl)) void my_cdecl_func_1 (void)
{
}

cdecl void my_cdecl_func_2 (void)
{
}

#ifdef __cplusplus
  [[gnu::cdecl]] void my_cdecl_func_3 (void)
  {
  }
#endif
```

The result is `#define cdecl`. So it must have been dropped in `<minwindef.h>` or elsewhere AFAICS.

**Comment by jwt27** [comment]
But Watt-32 isn't Windows-only, so I don't see why this macro must be introduced on other platforms too, when it can be avoided.

On Windows it isn't a problem since `[[gnu::cdecl]]` or `__attribute__((cdecl))` don't exist in MSVC.
