### ISSUE TITLE
WATT32S Help

### ISSUE THREAD

**Issue by eltoneo** [gvanem/Watt-32#71]
Hi,
RE: DOSBox-X
Building 'watt32s' DJGPP library trapped the follow error:
v v v
jgpp-receive.o -c receive.c
receive.c: In function ‘receive’
receive.c:95:29: error: invalid application of 'sizeof’ to incomplete type ‘struct sockaddr_ll'
   95 | ____________________sizeof(struct sockaddr_ll)
| ___________________________^~~~~~

make: xxx [djgpp.mak:172: build/djgpp/receive.o] Error 1
^ ^ ^
Can it be patched and which djgpp platform was source code built on?

**Comment by gvanem** [comment]
You must be using some old sources. Which?
With a `git clone ` of the master, `configur.bat djgpp` and a
pre-process command `c:\watt\src> make -f djgpp.mak receive.i`
you'll see that `struct sockaddr_ll` gets included from `$WATT_ROOT/inc/net/if_packe.h`.

**Comment by eltoneo** [comment]
> You must be using some old sources. Which? With a `git clone ` of the master, `configur.bat djgpp` and a pre-process command `c:\watt\src> make -f djgpp.mak receive.i` you'll see that `struct sockaddr_ll` gets included from `$WATT_ROOT/inc/net/if_packe.h`.
Hi,
SRC at [link](http://watt-32.net)
Also, your SRC at [link ](https://github.com/jay/wget/blob/master/msdos/Makefile.DJ) needs updating, using [link ](http://www.delorie.com/pub/djgpp/current/v2tk/ssl102us.zip) for functional SSL/TLS.  This library has proven functionality in this up to date DOS browser[ link](http://macall.net).
e

**Comment by gvanem** [comment]
Seems to be fixed. Closing.
